### ISSUE TITLE
i dont know why?System.TypeInitializationException of OpenTK.Graphics.GraphicsMode

### ISSUE THREAD

**Issue by lantianning** [Simie/EmpireSharp#1]
未处理System.TypeInitializationException
  HResult=-2146233036
  Message=“OpenTK.Graphics.GraphicsMode”的类型初始值设定项引发异常。
  Source=OpenTK
  TypeName=OpenTK.Graphics.GraphicsMode
  StackTrace:
       在 OpenTK.Graphics.GraphicsMode.get_Default()
       在 OpenTK.GameWindow..ctor() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\GameWindow.cs:行号 100
       在 Microsoft.Xna.Framework.OpenTKGameWindow.Initialize() 位置 e:\学习\源码\C#\游戏\EmpireSharp\MonoGame-3.0.0.0\MonoGame.Framework\Desktop\OpenTKGameWindow.cs:行号 256
       在 Microsoft.Xna.Framework.OpenTKGameWindow..ctor() 位置 e:\学习\源码\C#\游戏\EmpireSharp\MonoGame-3.0.0.0\MonoGame.Framework\Desktop\OpenTKGameWindow.cs:行号 127
       在 Microsoft.Xna.Framework.OpenTKGamePlatform..ctor(Game game) 位置 e:\学习\源码\C#\游戏\EmpireSharp\MonoGame-3.0.0.0\MonoGame.Framework\Desktop\OpenTKGamePlatform.cs:行号 105
       在 Microsoft.Xna.Framework.GamePlatform.Create(Game game) 位置 e:\学习\源码\C#\游戏\EmpireSharp\MonoGame-3.0.0.0\MonoGame.Framework\GamePlatform.cs:行号 96
       在 Microsoft.Xna.Framework.Game..ctor() 位置 e:\学习\源码\C#\游戏\EmpireSharp\MonoGame-3.0.0.0\MonoGame.Framework\Game.cs:行号 141
       在 EmpireSharp.Game.Modules.MonoGame.Shell..ctor(IKernel ioc) 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\EmpireSharp.Game\Modules\MonoGame\Shell.cs:行号 44
       在 DynamicInjector79f186c967334c05868da9cc90b03376(Object[] )
       在 Ninject.Activation.Providers.StandardProvider.Create(IContext context) 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\Dependencies\Ninject\src\Ninject\Activation\Providers\StandardProvider.cs:行号 74
       在 Ninject.Activation.Context.ResolveInternal(Object scope) 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\Dependencies\Ninject\src\Ninject\Activation\Context.cs:行号 159
       在 Ninject.Activation.Context.Resolve() 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\Dependencies\Ninject\src\Ninject\Activation\Context.cs:行号 125
       在 Ninject.ReadonlyKernel.Resolve(IRequest request, Boolean requestMissingBindings) 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\Dependencies\Ninject\src\Ninject\ReadonlyKernel.cs:行号 143
       在 Ninject.ReadonlyKernel.Resolve(IRequest request) 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\Dependencies\Ninject\src\Ninject\ReadonlyKernel.cs:行号 112
       在 Ninject.KernelBase.Resolve(IRequest request) 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\Dependencies\Ninject\src\Ninject\KernelBase.cs:行号 309
       在 Ninject.ResolutionExtensions.GetResolutionIterator(IResolutionRoot root, Type service, Func`2 constraint, IEnumerable`1 parameters, Boolean isOptional, Boolean isUnique) 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\Dependencies\Ninject\src\Ninject\Syntax\ResolutionExtensions.cs:行号 387
       在 Ninject.ResolutionExtensions.Get[T](IResolutionRoot root, IParameter[] parameters) 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\Dependencies\Ninject\src\Ninject\Syntax\ResolutionExtensions.cs:行号 37
       在 EmpireSharp.Game.Main.Run() 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\EmpireSharp.Game\Main.cs:行号 33
       在 EmpireSharp.Game.Program.Main() 位置 e:\学习\源码\C#\游戏\EmpireSharp-develop\EmpireSharp.Game\Program.cs:行号 34
  InnerException: System.TypeInitializationException
       HResult=-2146233036
       Message=“OpenTK.DisplayDevice”的类型初始值设定项引发异常。
       Source=OpenTK
       TypeName=OpenTK.DisplayDevice
       StackTrace:
            在 OpenTK.DisplayDevice.get_Default()
            在 OpenTK.Graphics.GraphicsMode.get_Default() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\Graphics\GraphicsMode.cs:行号 375
            在 OpenTK.NativeWindow..ctor() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\NativeWindow.cs:行号 61
            在 OpenTK.Platform.Windows.WinGraphicsMode..ctor() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\Platform\Windows\WinGraphicsMode.cs:行号 53
            在 OpenTK.Platform.Windows.WinFactory.CreateGraphicsMode() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\Platform\Windows\WinFactory.cs:行号 74
            在 OpenTK.Graphics.GraphicsMode..cctor() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\Graphics\GraphicsMode.cs:行号 37
       InnerException: System.MethodAccessException
            HResult=-2146233072
            Message=安全透明方法“OpenTK.Platform.Windows.WinDisplayDeviceDriver.RefreshDisplayDevices()”尝试通过方法“OpenTK.Platform.Windows.Functions.EnumDisplayDevices(System.String, Int32, OpenTK.Platform.Windows.WindowsDisplayDevice, Int32)”调用本机代码失败。方法必须是安全关键的或安全可靠关键的，才能调用本机代码。
            Source=OpenTK
            StackTrace:
                 在 OpenTK.Platform.Windows.WinDisplayDeviceDriver.RefreshDisplayDevices() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\Platform\Windows\WinDisplayDevice.cs:行号 113
                 在 OpenTK.Platform.Windows.WinDisplayDeviceDriver..ctor() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\Platform\Windows\WinDisplayDevice.cs:行号 45
                 在 OpenTK.Platform.Windows.WinFactory.CreateDisplayDeviceDriver() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\Platform\Windows\WinFactory.cs:行号 51
                 在 OpenTK.DisplayDevice..cctor() 位置 e:\学习\源码\C#\游戏\EmpireSharp\opentk-master\Source\OpenTK\DisplayDevice.cs:行号 65
            InnerException:

**Comment by Simie** [comment]
This project never got very far, and likely won't compile on any other machines but mine. Check out [openage](https://github.com/SFTtech/openage) for an open source AOE2 that is still going strong.

**Comment by lantianning** [comment]
I like your project is because I like playing the AOE2 game and I also know some C# language development. So I want to learn the game development through your project happily. About your project, I spent one day to find the related library and compile it successfully. But the compilation is not the main problem. The error is often occurred after the compiler successfully then to debug.  Could you send a complete compilation and running code and lib to me?Or could you tell the condition of running? Openage is written in C language and I do not intend to study. By contrast, I'm more interested in you project. Can you help me?
